apiVersion: v1
kind: ServiceAccount
metadata:
  name: infinidat-provisioner
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: infinidat-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get"]
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["infinidat-provisioner"]
    verbs: ["use"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-infinidat-provisioner
subjects:
  - kind: ServiceAccount
    name: infinidat-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: infinidat-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: ConfigMap
apiVersion: v1
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: provisionerconfig
  namespace: default
data:
  pool_name: default
  vol_prefix: vol
  management_address: http://172.17.72.58
  provision_type: THICK
  nfs_mount_options: hard, rsize=1M, wsize=1M
  nfs_unix_permissions: "777"
  nfs_export_permissions: RW
  max_fs: "100"
  max_volume: "100000"
  nfs_ssd_enabled: "false"
  nfs_no_root_squash: "true"
---
#echo -n "admin" | base64
#echo -n "123456" | base64
apiVersion: v1
kind: Secret
metadata:
  name: mgmt-api-credentials
type: Opaque
data:
  username: YWRtaW4=
  password: MTIzNDU2
  management_url: aHR0cDovLzE3Mi4xNy43Mi41OC8=
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: infinidat-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: infinidat-provisioner
    spec:
      serviceAccount: infinidat-provisioner
      containers:
        - name: infinidat-provisioner
          image: quay.io/nileshdsalunkhe/nfsprovi:latest
          env:
            - name: MGMT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mgmt-api-credentials
                  key: username
            - name: MGMT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mgmt-api-credentials
                  key: password
            - name: MGMT_URL
              valueFrom:
                secretKeyRef:
                  name: mgmt-api-credentials
                  key: management_url
          imagePullPolicy: "Always"
          volumeMounts:
            - name: export-volume
              mountPath: /export
      volumes:
        - name: export-volume
          hostPath:
            path: /tmp/infinidat-provisioner
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: infinidat-nfs-rw
provisioner: infinidat.com/nfs
parameters:
  pool_name: default
  networkspace: k8snw
  nfs_mount_options: hard,rsize=1M,wsize=1M
  nfs_export_permissions: RW
