kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-infinidat-provisioner
subjects:
  - kind: ServiceAccount
    name: infinidat-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: infinidat-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
