kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: infinidat-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: infinidat-provisioner
    spec:
      serviceAccount: infinidat-provisioner
      containers:
        - name: infinidat-provisioner
          image: quay.io/nileshdsalunkhe/nfsprovi:latest
          securityContext:
            capabilities:
              add:
                - DAC_READ_SEARCH
                - SYS_RESOURCE
          env:
            - name: MGMT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mgmt-api-credentials
                  key: username
            - name: MGMT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mgmt-api-credentials
                  key: password
            - name: MGMT_URL
              valueFrom:
                secretKeyRef:
                  name: mgmt-api-credentials
                  key: management_url
          imagePullPolicy: "Always"
          volumeMounts:
            - name: export-volume
              mountPath: /export
      volumes:
        - name: export-volume
          hostPath:
            path: /tmp/infinidat-provisioner
