#echo -n "admin" | base64
#echo -n "123456" | base64
apiVersion: v1
kind: Secret
metadata:
  name: mgmt-api-credentials
type: Opaque
data:
  username: YWRtaW4=
  password: MTIzNDU2
  management_url: aHR0cDovLzE3Mi4xNy43Mi41OA==